# Application
spring.application.name=loc-mns-back

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/locmns
spring.datasource.username=locmns_user
spring.datasource.password=locmns_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Server
server.port=8080