# Application
spring.application.name=loc-mns-back

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/locmns
spring.datasource.username=locmns_user
spring.datasource.password=locmns_pass

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080